### ISSUE TITLE
Disable no-animate for scrolling

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-plugin-no-jquery#65]
The `no-animate` rule says 'Prefer CSS transitions to $.animate', but for scrollTop/scrollLeft properties this is not possible. We should detect this edge case and disable the rule.

**Comment by edg2s** [comment]
I have a patch for this but we also need to decide if this requires a new rule?

Should `no-animate` still disable all uses of $.animate? Should we create a new rule that disables all CSS-transitionable uses of animate? Or add an `excludeScroll` rule option?

cc @jdforrester @Krinkle

**Comment by Krinkle** [comment]
Nice catch. While indeed not a CSS feature, there are native features that would be a preferred alternative still.

* https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
* https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

Demo: <https://codepen.io/Krinkle/full/vbQgQy>

The JS interface is supported in all major browsers (going back to IE8). The `smooth` option (which animates) has been supported in Firefox and Chrome for a little while, but missing still in Edge and Safari (~ 9% of WMF page views; Jan 2019; including no-js, Grade C, and bots).

They do, however, gracefully fall back to a regular jump in all browsers.

Okay to degrade? I don't know. Might be a bit soon. Or maybe it depends on the use case.

**Comment by edg2s** [comment]
What about when more complex scroll destinations are required, e.g. element.offsetY - toolbar.height?

**Comment by edg2s** [comment]
> but missing still in Edge and Safari (~ 9%

Isn't iOS 23% of pageviews?

**Comment by Krinkle** [comment]
> What about when more complex scroll destinations, e.g. element.offsetY - toolbar.height?

For arbitrary coordinate destinations, there is `scrollTo(x,y)`, which also supports the same aforementioned "smooth" option (<https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo>).

For coordinate destinations within a scrollable element (not window/iframe), you can set the same `scrollTop` and `scrollLeft` properties that we set today, but without `$.animate` and they'll automatically animate as needed by setting `scroll-behavior: smooth;` in CSS.

Check the demo at <https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop>, set  `scroll-behavior: smooth;` on `div#idDiv` and then assign `$0.scollTop = 200` in the console, and you'll see it animate.

> Isn't iOS 23% of pageviews?

Yes, I was counting desktop browsers only.

I made the assumption that for most use cases on mobile, the animation would not be applicable or, undesirable. For example, when the navigation panel is not visible at the same time as the content anyway (a modal, slide over menu). Or, when visible at the same time an one might not want an animation. Because, on desktop one is more likely to have a sense of the whole document if everything is less than 1 or 2 pages apart, but on mobile the same document might require tons and tons of scrolling to get anywhere, hence one would better use the navigator for your sense of context and order (no need for scroll animations to illustrate relative location, as one couldn't easily get back by scrolling).

It would add very little value and yet might cost you valuable time and might make you lose the sense of the response being immediate. Also keeping in mind that due to the distance being much longer on mobile (relatively speaking) the animations will either require significantly more time to complete (becoming a nuisance) or require such as high speed that the visual effect is indistinguishable from a shockery-whizywoo state transition in a slidedeck, with no expectation that the previous section is for sure on the same page still and reachable by scrolling.

Anyhow, I'm not saying those are the only use cases for assisted scrolling. There are lots more in fact. I just think that our requirement shouldn't be arbitrary destinations, because the only reason they appear arbitrary today is because we didn't have these features previously.

Another one is scroll snapping: <https://webkit.org/blog/4017/scroll-snapping-with-css-snap-points/>, <https://webkit.org/demos/scroll-snap/>. (This one's supported in Mobile Safari as well.)

**Comment by edg2s** [comment]
Our current use case: https://phabricator.wikimedia.org/T210630#4938902

**Comment by Krinkle** [comment]
@edg2s Right, seems like scrollIntoView would cover that, but yeah, Mobile Safari, so $.animate for now seems totally fine there. I don't mind exempting all scroll animations. But perhaps it's not worth the time to write a rule of it, instead of a simple inline eslint exemption where we need it.
